name: PR Checks

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Cache Gradle build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
            composeApp/build
            build
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run ktlint check
        run: ./gradlew ktlintCheck

      - name: Run Android unit tests
        run: ./gradlew testDebugUnitTest

      - name: Compile Android
        run: ./gradlew assembleDebug

      - name: Compile iOS
        run: ./gradlew linkDebugFrameworkIosSimulatorArm64

      - name: Generate coverage report
        run: |
          ./gradlew koverHtmlReport koverPrintCoverage > coverage_output.txt
          COVERAGE=$(grep "application line coverage" coverage_output.txt | grep -oE '[0-9]+\.[0-9]+%')
          echo "## Code Coverage Report :chart_with_upwards_trend:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Coverage:** $COVERAGE" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Full report generated at: \`composeApp/build/reports/kover/html/index.html\`" >> $GITHUB_STEP_SUMMARY
          cat coverage_output.txt
